#include <algorithm>
#include <ios>
#include <vector>
#include <iostream>
#include <iomanip>
#include <string>
#include <stdexcept>
#include "Student_info.h"
#include "grade.h"

using std::cin;
using std::out;
using std::endl;
using std::domain_error;
using std::max;
using std::setprecision;
using std::setw;
using std::sort;
using std::string;
using std::streamize;
using std::vector;
